"""
===========================================================
Indian Multi-Region Electricity Demand Forecasting — Interactive Dashboard — Interactive Dashboard
Indian Multi-Region Electricity Demand Forecasting
===========================================================

Run from the project root with:

    streamlit run dashboard/app.py

This dashboard reads the outputs your pipeline already produces —
it does NOT retrain or re-run any models. It just visualizes:

  results/xgboost/{region}_predictions.csv   (Actual, Naive, XGBoost)
  results/lstm/{region}_predictions.csv      (Actual, Prediction)
  results/lstm/{region}_metrics.csv
  reports/metrics/model_summary.csv          (XGBoost metrics, all regions)
  reports/metrics/{region}_residual_statistics.csv
  reports/feature_importance/{region}_importance.csv / .png
  reports/shap/{region}_summary.png / {region}_bar.png
  reports/residuals/{region}_residual.png
  reports/plots/{region}_prediction.png
  data/features/{region}_features.csv        (used only for datetime axis)
===========================================================
"""

import os
from pathlib import Path

import pandas as pd
import streamlit as st
import plotly.graph_objects as go

# ==========================================================
# Paths
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

DATA_FEATURES_DIR = BASE_DIR / "data" / "features"
RESULTS_XGB_DIR = BASE_DIR / "results" / "xgboost"
RESULTS_LSTM_DIR = BASE_DIR / "results" / "lstm"
# NOTE: XGBoost report artifacts now live under an "XGBoost" subfolder
# after the reports/ restructure. REPORT_METRICS_DIR stays XGBoost-only
# since model_summary.csv and residual_statistics.csv are only ever
# produced by evaluate.py for XGBoost. SHAP / feature importance /
# residuals now have per-model versions and are looked up dynamically
# in each tab using `model_folder` instead of a fixed constant.
REPORT_METRICS_DIR = BASE_DIR / "reports" / "metrics" / "XGBoost"
REPORT_PLOTS_DIR = BASE_DIR / "reports" / "plots" / "XGBoost"

REGIONS = ["northern", "western", "eastern", "southern", "northeastern"]

st.set_page_config(
    page_title="Indian Multi-Region Electricity Demand Forecasting — Interactive Dashboard",
    page_icon="⚡",
    layout="wide",
)

# ==========================================================
# Cached loaders — everything here reads existing files only
# ==========================================================

@st.cache_data
def load_csv(path: Path):
    if not path.exists():
        return None
    return pd.read_csv(path)


@st.cache_data
def load_datetime_tail(region: str, n_rows: int):
    """
    Best-effort reconstruction of a datetime axis for a predictions file.

    train.py / train_lstm.py use a chronological (non-shuffled) train/test
    split, so the test set is the LAST n_rows of the feature file in time
    order. We recover those timestamps from data/features/{region}_features.csv.
    This is an approximation — it will be exact for XGBoost (same split
    logic) but only approximate for LSTM (sequence windowing shifts the
    start index slightly).
    """
    feat_path = DATA_FEATURES_DIR / f"{region}_features.csv"
    if not feat_path.exists():
        return None
    try:
        dt = pd.read_csv(feat_path, usecols=["datetime"])["datetime"]
        if n_rows > len(dt):
            return None
        return pd.to_datetime(dt.tail(n_rows).reset_index(drop=True))
    except Exception:
        return None


def region_label(region: str) -> str:
    return region.replace("_", " ").title()


# ==========================================================
# Sidebar — controls
# ==========================================================

st.sidebar.title("⚡ Indian Multi-Region Electricity Demand Forecasting — Interactive Dashboard")
st.sidebar.caption("Multi-Region Electricity Demand Forecasting — India")

selected_region = st.sidebar.selectbox(
    "Region",
    REGIONS,
    format_func=region_label,
)

selected_model = st.sidebar.radio(
    "Model",
    ["XGBoost", "LSTM"],
)

# Maps the model toggle to the report subfolder naming convention on disk
# (reports/<type>/XGBoost/... and reports/<type>/lstm/...).
model_folder = "XGBoost" if selected_model == "XGBoost" else "lstm"

st.sidebar.divider()
st.sidebar.caption(
    "This dashboard visualizes outputs already generated by the "
    "pipeline (`train.py`, `train_lstm.py`, `shap_analysis.py`, "
    "`evaluate.py`). It does not train or re-run models."
)

# ==========================================================
# Header
# ==========================================================

st.title(f"{region_label(selected_region)} Region — Demand Forecast")
st.caption(f"Model: **{selected_model}**")

tab_forecast, tab_metrics, tab_shap, tab_extra = st.tabs(
    ["📈 Forecast", "📊 Metrics", "🔍 SHAP Explainability", "🧩 Feature Importance & Residuals"]
)

# ==========================================================
# TAB 1 — Forecast: historical demand vs prediction
# ==========================================================

with tab_forecast:

    if selected_model == "XGBoost":
        preds = load_csv(RESULTS_XGB_DIR / f"{selected_region}_predictions.csv")

        if preds is None:
            st.warning(f"No XGBoost predictions found for {region_label(selected_region)}.")
        else:
            show_naive = st.checkbox("Show naive baseline", value=False)

            n_points = st.slider(
                "Points to display (most recent)",
                min_value=50,
                max_value=len(preds),
                value=min(500, len(preds)),
                step=50,
            )

            plot_df = preds.tail(n_points).reset_index(drop=True)
            dt_axis = load_datetime_tail(selected_region, len(preds))
            x_axis = (
                dt_axis.tail(n_points).reset_index(drop=True)
                if dt_axis is not None
                else plot_df.index
            )

            fig = go.Figure()
            fig.add_trace(go.Scatter(x=x_axis, y=plot_df["Actual"], name="Actual", line=dict(width=2)))
            fig.add_trace(go.Scatter(x=x_axis, y=plot_df["XGBoost"], name="XGBoost Forecast", line=dict(width=2, dash="dot")))
            if show_naive and "Naive" in plot_df.columns:
                fig.add_trace(go.Scatter(x=x_axis, y=plot_df["Naive"], name="Naive Baseline", line=dict(width=1, dash="dash")))

            fig.update_layout(
                xaxis_title="Time" if dt_axis is not None else "Time step (test set)",
                yaxis_title="Demand (MW)",
                legend=dict(orientation="h", yanchor="bottom", y=1.02),
                height=500,
                margin=dict(t=40),
            )
            st.plotly_chart(fig, use_container_width=True)

            if dt_axis is None:
                st.caption(
                    "⚠️ No matching datetime column found in "
                    f"`data/features/{selected_region}_features.csv` — showing raw time-step index instead."
                )

    else:  # LSTM
        preds = load_csv(RESULTS_LSTM_DIR / f"{selected_region}_predictions.csv")

        if preds is None:
            st.warning(
                f"No LSTM predictions found for {region_label(selected_region)} yet. "
                "Run `src/train_lstm.py` for this region to populate `results/lstm/`."
            )
        else:
            n_points = st.slider(
                "Points to display (most recent)",
                min_value=50,
                max_value=len(preds),
                value=min(500, len(preds)),
                step=50,
                key="lstm_points",
            )

            plot_df = preds.tail(n_points).reset_index(drop=True)
            dt_axis = load_datetime_tail(selected_region, len(preds))
            x_axis = (
                dt_axis.tail(n_points).reset_index(drop=True)
                if dt_axis is not None
                else plot_df.index
            )

            fig = go.Figure()
            fig.add_trace(go.Scatter(x=x_axis, y=plot_df["Actual"], name="Actual", line=dict(width=2)))
            fig.add_trace(go.Scatter(x=x_axis, y=plot_df["Prediction"], name="LSTM Forecast", line=dict(width=2, dash="dot")))

            fig.update_layout(
                xaxis_title="Time" if dt_axis is not None else "Time step (test set)",
                yaxis_title="Demand (MW)",
                legend=dict(orientation="h", yanchor="bottom", y=1.02),
                height=500,
                margin=dict(t=40),
            )
            st.plotly_chart(fig, use_container_width=True)

            if dt_axis is None:
                st.caption("⚠️ Showing raw time-step index — datetime alignment unavailable.")
            else:
                st.caption(
                    "⚠️ Datetime axis is approximate for LSTM (sequence windowing "
                    "shifts the exact start index vs. the raw feature file)."
                )

    # Existing static evaluation plot (from evaluate.py), if present
    static_plot = REPORT_PLOTS_DIR / f"{selected_region}_prediction.png"
    if static_plot.exists():
        with st.expander("View saved evaluation plot (from evaluate.py)"):
            st.image(str(static_plot), use_container_width=True)

# ==========================================================
# TAB 2 — Metrics
# ==========================================================

with tab_metrics:

    if selected_model == "XGBoost":
        summary = load_csv(REPORT_METRICS_DIR / "model_summary.csv")

        if summary is None:
            st.warning("`reports/metrics/model_summary.csv` not found.")
        else:
            row = summary[summary["Region"].str.lower() == selected_region]
            if row.empty:
                st.warning(f"No XGBoost metrics found for {region_label(selected_region)}.")
            else:
                row = row.iloc[0]
                c1, c2, c3, c4 = st.columns(4)
                c1.metric("MAE", f"{row['MAE']:.2f} MW")
                c2.metric("RMSE", f"{row['RMSE']:.2f} MW")
                c3.metric("MAPE", f"{row['MAPE']:.2f}%")
                c4.metric("R²", f"{row['R2']:.4f}")

    else:  # LSTM
        metrics = load_csv(RESULTS_LSTM_DIR / f"{selected_region}_metrics.csv")

        if metrics is None:
            st.warning(
                f"No LSTM metrics found for {region_label(selected_region)} yet. "
                "Run `src/train_lstm.py` for this region to populate `results/lstm/`."
            )
        else:
            row = metrics.iloc[0]
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("MAE", f"{row['MAE']:.2f} MW")
            c2.metric("RMSE", f"{row['RMSE']:.2f} MW")
            c3.metric("MAPE", f"{row['MAPE']:.2f}%")
            c4.metric("R²", f"{row['R2']:.4f}")

        # Training history, if available
        history_plot = BASE_DIR / "reports" / "training_history" / f"{selected_region}_training_loss.png"
        if history_plot.exists():
            st.subheader("Training History")
            st.image(str(history_plot), use_container_width=True)

    st.divider()

    # Residual statistics (available for XGBoost regardless of model toggle,
    # since evaluate.py computes these from the XGBoost run)
    resid_stats = load_csv(REPORT_METRICS_DIR / f"{selected_region}_residual_statistics.csv")
    if resid_stats is not None:
        st.subheader("Residual Statistics (XGBoost)")
        st.dataframe(resid_stats, use_container_width=True, hide_index=True)

# ==========================================================
# TAB 3 — SHAP Explainability
# ==========================================================

with tab_shap:
    st.caption(
        "SHAP values show how much each feature pushed a given prediction "
        "above or below the average forecast."
    )

    shap_dir = BASE_DIR / "reports" / "shap" / model_folder
    summary_img = shap_dir / f"{selected_region}_summary.png"
    bar_img = shap_dir / f"{selected_region}_bar.png"

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Summary plot** (feature impact & direction)")
        if summary_img.exists():
            st.image(str(summary_img), use_container_width=True)
        else:
            st.info(
                "SHAP summary plot not found for this region. "
                + ("Run `src/shap_analysis.py`."
                   if selected_model == "XGBoost"
                   else "Run `src/shap_analysis_lstm.py`.")
            )

    with col2:
        st.markdown("**Bar plot** (mean absolute feature impact)")
        if bar_img.exists():
            st.image(str(bar_img), use_container_width=True)
        else:
            st.info(
                "SHAP bar plot not found for this region. "
                + ("Run `src/shap_analysis.py`."
                   if selected_model == "XGBoost"
                   else "Run `src/shap_analysis_lstm.py`.")
            )

# ==========================================================
# TAB 4 — Feature Importance & Residuals
# ==========================================================

with tab_extra:
    featimp_dir = BASE_DIR / "reports" / "feature_importance" / model_folder
    residuals_dir = BASE_DIR / "reports" / "residuals" / model_folder

    col1, col2 = st.columns(2)

    with col1:
        st.subheader(f"Feature Importance ({selected_model})")
        fi_csv = load_csv(featimp_dir / f"{selected_region}_importance.csv")
        fi_img = featimp_dir / f"{selected_region}_importance.png"

        if fi_img.exists():
            st.image(str(fi_img), use_container_width=True)
        if fi_csv is not None:
            st.dataframe(
                fi_csv.sort_values("Importance", ascending=False).head(10),
                use_container_width=True,
                hide_index=True,
            )
        if fi_csv is None and not fi_img.exists():
            st.info(
                "Feature importance data not found for this region. "
                + ("Run `src/evaluate.py`."
                   if selected_model == "XGBoost"
                   else "Run `src/shap_analysis_lstm.py`.")
            )

    with col2:
        st.subheader(f"Residual Plot ({selected_model})")
        resid_img = residuals_dir / f"{selected_region}_residual.png"
        if resid_img.exists():
            st.image(str(resid_img), use_container_width=True)
        else:
            st.info(
                "Residual plot not found for this region. "
                + ("Run `src/evaluate.py`."
                   if selected_model == "XGBoost"
                   else "Run `src/evaluate_lstm.py`.")
            )
